<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJx6xP0E\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJx6xP0E/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJx6xP0E.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJx6xP0E\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJx6xP0E\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jx6xP0E',
    'container.build_id' => '4c4fc0ea',
    'container.build_time' => 1641221011,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJx6xP0E');
